FROM ubuntu:20.04

RUN DEBIAN_FRONTEND="noninteractive" apt-get update && apt-get -y install tzdata

RUN apt-get update \
  && apt-get install -y \
      clang-18 \
      cmake \
      gdb \
      git \
      m4 \
      unzip \
      valgrind \
      wget \
  && apt-get clean

ENV CC="/usr/bin/clang-18"
ENV CXX="/usr/bin/clang++-18"

RUN cd / && \
    wget https://gmplib.org/download/gmp/gmp-6.3.0.tar.xz && \
    tar -xf gmp-6.3.0.tar.xz

RUN cd gmp-6.3.0 && \
    ./configure --enable-cxx && \
    make -j10

RUN cd gmp-6.3.0 && \
#   make -j10 check && \
    make install


RUN cd / && \
    wget https://github.com/arminbiere/cadical/archive/refs/tags/rel-2.1.3.zip && \
    unzip rel-2.1.3.zip

RUN cd cadical-rel-2.1.3 && \
    ./configure && \
    make -j10 && \
    mkdir include lib && \
    cp src/cadical.hpp ./include/ && \
    cp build/libcadical.a ./lib/


RUN cd / && \
    wget https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz && \
    tar -xf flex-2.6.4.tar.gz
RUN cd flex-2.6.4 && \
    ./configure && \
    make -j10
RUN cd flex-2.6.4 && \
#   make -j10 check && \
    make install

RUN cd / && \
    wget https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.gz && \
    tar -xf bison-3.8.2.tar.gz
RUN cd bison-3.8.2 && \
    ./configure && \
    make -j10
RUN cd bison-3.8.2 && \
#   make -j10 check && \
    make install

ENV CMAKE_PREFIX_PATH="/cadical-rel-2.1.3/"

RUN rm /usr/local/lib/libfl.so*
RUN rm /usr/local/lib/libgmp.so*
RUN rm /usr/local/lib/libgmpxx.so*

# for ODEs... all installs from dReal3
RUN apt-get update \
  && apt-get install -y \
      build-essential \
      autoconf \
      automake \
      libtool \
      pkg-config \
      software-properties-common \
      texinfo \
      python python3 python-dev python3-dev



# BEGIN DREAL BUILD
RUN  mkdir /dreal/
COPY src/ /dreal/src
COPY test/ /dreal/test
COPY CMakeLists.txt /dreal/CMakeLists.txt
COPY FULL_BUILD.sh /dreal/FULL_BUILD.sh
RUN /dreal/FULL_BUILD.sh

WORKDIR /dreal/gcc_build/
