FROM ubuntu:24.04

RUN DEBIAN_FRONTEND="noninteractive" apt-get update && apt-get -y install tzdata

RUN apt-get update \
  && apt-get install -y \
      clang-18 \
      cmake \
      gdb \
      git \
      m4 \
      unzip \
      valgrind \
      wget \
  && apt-get clean

ENV CC="/usr/bin/clang-18"
ENV CXX="/usr/bin/clang++-18"

RUN apt-get install -y xz-utils
RUN cd / && \
    wget https://gmplib.org/download/gmp/gmp-6.3.0.tar.xz && \
    tar -xf gmp-6.3.0.tar.xz

RUN cd gmp-6.3.0 && \
    ./configure --enable-cxx && \
    make -j10

RUN cd gmp-6.3.0 && \
#   make -j10 check && \
    make install


RUN cd / && \
    wget https://github.com/arminbiere/cadical/archive/refs/tags/rel-3.0.0.zip && \
    unzip rel-3.0.0.zip

RUN cd cadical-rel-3.0.0 && \
    ./configure && \
    make -j10 && \
    mkdir include lib && \
    cp src/cadical.hpp ./include/ && \
    cp build/libcadical.a ./lib/


RUN cd / && \
    wget https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz && \
    tar -xf flex-2.6.4.tar.gz
RUN cd flex-2.6.4 && \
    ./configure && \
    make -j10
RUN cd flex-2.6.4 && \
#   make -j10 check && \
    make install

RUN cd / && \
    wget https://ftp.gnu.org/gnu/bison/bison-3.8.2.tar.gz && \
    tar -xf bison-3.8.2.tar.gz
RUN cd bison-3.8.2 && \
    ./configure && \
    make -j10
RUN cd bison-3.8.2 && \
#   make -j10 check && \
    make install

ENV CMAKE_PREFIX_PATH="/cadical-rel-3.0.0/"

RUN rm /usr/local/lib/libfl.so*
RUN rm /usr/local/lib/libgmp.so*
RUN rm /usr/local/lib/libgmpxx.so*

# BEGIN DREAL BUILD
# The IBEX source-build ExternalProject clones from
# https://github.com/ncsys-lab/ibex-lib at the pinned dreal-perf-patches sha
# (see CMakeLists.txt's IBEX_GIT_REPOSITORY / IBEX_GIT_TAG cache variables).
# Override either at `docker build --build-arg` time if pointing at a local
# checkout — the default needs only outbound HTTPS from the build sandbox.
#
# Invocation:
#   docker build -f Dockerfile.dreal_ubuntu -t dreal-linux-verify .
RUN  mkdir /dreal/
COPY src/ /dreal/src
COPY test/ /dreal/test
COPY CMakeLists.txt /dreal/CMakeLists.txt
COPY FULL_BUILD.sh /dreal/FULL_BUILD.sh
RUN /dreal/FULL_BUILD.sh

WORKDIR /dreal/gcc_build/
