/*
   Copyright 2026 dReal contributors

   Licensed under the Apache License, Version 2.0 (the "License").
*/
//
// Gaol transcendental bit-identity + adversarial soundness gate.
//
// Purpose: this file is the *verifier* for the two gaol ARM64 rounding levers
// (Lever 1: inline aarch64 fpcr fast-path for round_*(); Lever 2: batch the
// nearest-rounding region in gaol_interval.cpp).  Both levers must change only
// *when/how* the FPU rounding mode is switched -- never the values computed --
// so every gaol interval function must yield a BIT-IDENTICAL interval after each
// lever vs the pristine baseline.
//
// Two independent layers:
//
//   (A) Bit-identical golden  [the exact, unforgeable lever gate]
//       A committed, inspectable golden table (gaol_transcendental_golden.inc)
//       captured from the BASELINE (pre-lever) build records, for a wide
//       adversarial grid, the exact output-endpoint bits of every gaol interval
//       function.  This test recomputes each case and asserts the result bits
//       reproduce the golden bit-for-bit.  A single changed bit fails it.
//       The golden is regenerated by the DISABLED_Generate test (run once on the
//       baseline) -- it is captured from the solver, never hand-authored.
//
//   (B) Independent enclosure + tightness  [adversarial sanity net]
//       Golden-independent.  For each case it samples many points x in X
//       (endpoints + analytic extrema + interior) and asserts the gaol interval
//       ENCLOSES the libm reference value (soundness) and is not grossly too wide
//       (tightness).  libm is itself only ~1 ulp accurate, so this layer carries
//       a few-ulp reference-error tolerance and is a coarse net catching sign
//       flips / wrong magnitude / NaN / non-enclosure -- it validates that the
//       baseline golden we freeze is itself sound, rather than enshrining a bug.
//       Layer (A) remains the exact bit-level gate.
//
// All test code lives in dReal; nothing is added to the ibex-fork.  Gaol
// interval arithmetic is sound only under FE_UPWARD, so every gaol call is made
// inside an UpwardRoundingScope; the libm reference is computed inside a nested
// NearestRoundingScope.
//
// Regenerate the golden (run against the baseline build, from the build dir):
//   GAOL_GOLDEN_OUT=<repo>/test/dreal/util/test/gaol_transcendental_golden.inc \
//     ./dreal4_cmake_test \
//     --gtest_filter='*GaolTranscendental*Generate*' \
//     --gtest_also_run_disabled_tests
//
#include <cfenv>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

#include <gtest/gtest.h>

#include "ibex.h"

#include "dreal/util/rounding.h"

namespace dreal {
namespace {

using ibex::Interval;

// ---------------------------------------------------------------------------
// Bit helpers (never compare doubles with ==; bits handle +-0, +-inf, NaN).
// ---------------------------------------------------------------------------
uint64_t Bits(double d) {
  uint64_t b{};
  std::memcpy(&b, &d, sizeof(b));
  return b;
}
double FromBits(uint64_t b) {
  double d{};
  std::memcpy(&d, &b, sizeof(d));
  return d;
}

// ---------------------------------------------------------------------------
// The adversarial grid.  A case is a function name + one (unary) or two
// (binary) input intervals.  Inputs are normalized through Interval construction
// so the stored/reconstructed endpoint bits are idempotent.
// ---------------------------------------------------------------------------
struct Case {
  std::string func;
  Interval x;
  Interval y;     // unused for unary (kept as a point 0)
  bool binary;
};

Case U(const std::string& f, double lo, double hi) {
  return Case{f, Interval(lo, hi), Interval(0.0), false};
}
Case B(const std::string& f, double xlo, double xhi, double ylo, double yhi) {
  return Case{f, Interval(xlo, xhi), Interval(ylo, yhi), true};
}
// pow(x, integer n): encode n as the point interval [n, n].
Case PowI(double xlo, double xhi, int n) {
  return Case{"pow_int", Interval(xlo, xhi), Interval(static_cast<double>(n)),
              true};
}

const double kPi = M_PI;
const double kInf = std::numeric_limits<double>::infinity();
const double kDenormMin = std::numeric_limits<double>::denorm_min();
const double kTiny = std::numeric_limits<double>::min();  // smallest normal
const double kHuge = 1e300;

// Build the full grid.  Tailored per function to its branch structure (the exact
// logic a rounding bug disturbs): extrema, poles, domain edges, periods, huge
// magnitudes, subnormals, point intervals, and tiny vs wide widths.
std::vector<Case> BuildGrid() {
  std::vector<Case> g;

  // sin / cos: near 0; straddling +-pi/2,+-pi,+-3pi/2 (extrema, gaol::cos
  // even/odd-m branch); >= one full period (must yield [-1,1]); huge magnitude
  // (Payne-Hanek); points; subnormal/negative; tiny vs wide.
  for (const char* f : {"sin", "cos"}) {
    g.push_back(U(f, -1e-9, 1e-9));
    g.push_back(U(f, -0.4, 0.4));
    g.push_back(U(f, kPi / 2 - 0.1, kPi / 2 + 0.1));
    g.push_back(U(f, -kPi / 2 - 0.1, -kPi / 2 + 0.1));
    g.push_back(U(f, kPi - 0.1, kPi + 0.1));
    g.push_back(U(f, -kPi - 0.1, -kPi + 0.1));
    g.push_back(U(f, 3 * kPi / 2 - 0.1, 3 * kPi / 2 + 0.1));
    g.push_back(U(f, 0.0, 2 * kPi));            // full period -> [-1,1]
    g.push_back(U(f, -7.0, 7.0));               // > 2 periods
    g.push_back(U(f, 0.3, 0.3));                // point (inexact)
    g.push_back(U(f, 1.0, 1.0));                // point (exact arg)
    g.push_back(U(f, 100.0, 100.0 + 0.5));      // moderate magnitude
    g.push_back(U(f, 1e8, 1e8 + 1.0));          // large
    g.push_back(U(f, kDenormMin, kDenormMin));  // subnormal point
    g.push_back(U(f, -3.0, -2.9));
    g.push_back(U(f, 1000.5, 1000.6));
  }

  // tan: near 0; approaching +-pi/2 poles (gaol returns universe if a pole is
  // crossed -- stay strictly inside one branch); negative; point; large
  // (>2^52 -> universe).
  g.push_back(U("tan", -1e-9, 1e-9));
  g.push_back(U("tan", -0.4, 0.4));
  g.push_back(U("tan", kPi / 2 - 0.3, kPi / 2 - 0.1));    // near +pole, inside
  g.push_back(U("tan", -kPi / 2 + 0.1, -kPi / 2 + 0.3));  // near -pole, inside
  g.push_back(U("tan", 0.7, 0.7));                        // point
  g.push_back(U("tan", -1.2, -1.0));
  g.push_back(U("tan", 1e16, 1e16 + 1.0));  // > 2^52 -> universe branch

  // exp: overflow (large +), underflow (large - -> 0/subnormal), around 0, point.
  g.push_back(U("exp", -1e-9, 1e-9));
  g.push_back(U("exp", -1.0, 1.0));
  g.push_back(U("exp", 700.0, 710.0));    // near overflow
  g.push_back(U("exp", 709.7, 709.8));    // straddle overflow boundary
  g.push_back(U("exp", -745.0, -740.0));  // underflow to subnormal
  g.push_back(U("exp", -1e4, -1e3));      // hard underflow -> [0, tiny]
  g.push_back(U("exp", 0.5, 0.5));        // point
  g.push_back(U("exp", -30.0, 30.0));     // wide

  // log: near 0+ (strict-ub==0 / (-inf,-DBL_MAX] case, gaol patch #8), near 1
  // (cancellation), exactly 1, large, point.
  g.push_back(U("log", kDenormMin, kDenormMin));
  g.push_back(U("log", kTiny, 2 * kTiny));
  g.push_back(U("log", 1e-300, 1e-290));
  g.push_back(U("log", 1.0 - 1e-12, 1.0 + 1e-12));  // cancellation near 1
  g.push_back(U("log", 1.0, 1.0));                  // log(1)=0 exactly
  g.push_back(U("log", 0.5, 2.0));
  g.push_back(U("log", 1e300, 1e308));
  g.push_back(U("log", 2.7, 2.7));  // point

  // asin / acos: edges +-1 (derivative -> inf), interior, 0, just-outside-domain
  // (gaol intersects with [-1,1]).
  for (const char* f : {"asin", "acos"}) {
    g.push_back(U(f, -1.0, -1.0 + 1e-12));
    g.push_back(U(f, 1.0 - 1e-12, 1.0));
    g.push_back(U(f, -1.0, 1.0));     // full domain
    g.push_back(U(f, -0.5, 0.5));
    g.push_back(U(f, 0.0, 0.0));      // point
    g.push_back(U(f, -2.0, 0.3));     // left clipped to [-1, .3]
    g.push_back(U(f, 0.3, 2.0));      // right clipped to [.3, 1]
    g.push_back(U(f, 0.123, 0.123));  // point inexact
  }

  // atan: large (-> +-pi/2), 0, negative, point.
  g.push_back(U("atan", -1e-9, 1e-9));
  g.push_back(U("atan", -1.0, 1.0));
  g.push_back(U("atan", kHuge, kInf));   // -> approaches pi/2
  g.push_back(U("atan", -kInf, -kHuge));
  g.push_back(U("atan", 5.0, 5.0));      // point
  g.push_back(U("atan", -1e8, 1e8));

  // sinh / cosh: overflow, 0 (cosh has the 0-in-I branch -> min 1), negative,
  // point.
  for (const char* f : {"sinh", "cosh"}) {
    g.push_back(U(f, -1e-9, 1e-9));
    g.push_back(U(f, -1.0, 1.0));    // straddles 0 (cosh special branch)
    g.push_back(U(f, 700.0, 710.0)); // overflow region
    g.push_back(U(f, -710.0, -700.0));
    g.push_back(U(f, 0.0, 0.0));     // point at 0
    g.push_back(U(f, 2.5, 2.5));     // point
    g.push_back(U(f, -3.0, -2.0));
  }

  // tanh: saturates to +-1; 0; large; point.
  g.push_back(U("tanh", -1e-9, 1e-9));
  g.push_back(U("tanh", -1.0, 1.0));
  g.push_back(U("tanh", 20.0, 40.0));   // saturated +1
  g.push_back(U("tanh", -40.0, -20.0)); // saturated -1
  g.push_back(U("tanh", 0.7, 0.7));     // point

  // sqrt: 0, near 0, large, point, wide.
  g.push_back(U("sqrt", 0.0, 0.0));
  g.push_back(U("sqrt", 0.0, 4.0));
  g.push_back(U("sqrt", kDenormMin, kDenormMin));
  g.push_back(U("sqrt", 2.0, 2.0));   // point (irrational result)
  g.push_back(U("sqrt", 1e-300, 1e-290));
  g.push_back(U("sqrt", 1.0, 1e300));
  g.push_back(U("sqrt", 0.25, 0.25)); // exact result

  // pow(x, integer n): negative base, even/odd exponent (gaol's ipow branch),
  // 0 exponent, point, fractional handled below.
  g.push_back(PowI(-2.0, 3.0, 2));   // straddles 0, even -> [0, max]
  g.push_back(PowI(-2.0, 3.0, 3));   // odd
  g.push_back(PowI(2.0, 2.0, 10));   // point base
  g.push_back(PowI(-3.0, -2.0, 4));  // negative base, even
  g.push_back(PowI(-3.0, -2.0, 5));  // negative base, odd
  g.push_back(PowI(0.5, 1.5, 0));    // exponent 0 -> [1,1]
  g.push_back(PowI(1.1, 1.2, 7));

  // pow(x, y) interval exponent (fractional, gaol patch #8): positive base.
  g.push_back(B("pow", 2.0, 2.0, 0.5, 0.5));   // sqrt(2)
  g.push_back(B("pow", 1.5, 3.0, 0.3, 0.7));
  g.push_back(B("pow", 0.1, 0.2, 2.0, 3.0));
  g.push_back(B("pow", 10.0, 10.0, -1.0, -1.0));  // 1/10

  // +  -  *  /  basic-op sweep over inexact / sign-straddling / large operands.
  const double a0 = 0.1, a1 = 0.3, b0 = -0.2, b1 = 0.7;
  for (const char* op : {"add", "sub", "mul", "div"}) {
    g.push_back(B(op, a0, a1, b0, b1));
    g.push_back(B(op, -1.0, 1.0, 0.3, 0.3));    // y point inexact
    g.push_back(B(op, 1e8, 1e8 + 1.0, 3.0, 3.0));
    g.push_back(B(op, -5.0, -3.0, 2.0, 4.0));
  }
  // division by a sign-straddling interval (gaol returns universe / split).
  g.push_back(B("div", 1.0, 2.0, -1.0, 1.0));
  g.push_back(B("div", 1.0, 1.0, 3.0, 3.0));  // 1/3, both points inexact

  return g;
}

// Dispatch a case to the actual gaol/ibex computation. MUST run under FE_UPWARD.
Interval Apply(const Case& c) {
  const Interval& X = c.x;
  const Interval& Y = c.y;
  const std::string& f = c.func;
  if (f == "sin") return ibex::sin(X);
  if (f == "cos") return ibex::cos(X);
  if (f == "tan") return ibex::tan(X);
  if (f == "exp") return ibex::exp(X);
  if (f == "log") return ibex::log(X);
  if (f == "asin") return ibex::asin(X);
  if (f == "acos") return ibex::acos(X);
  if (f == "atan") return ibex::atan(X);
  if (f == "sinh") return ibex::sinh(X);
  if (f == "cosh") return ibex::cosh(X);
  if (f == "tanh") return ibex::tanh(X);
  if (f == "sqrt") return ibex::sqrt(X);
  if (f == "pow_int") return ibex::pow(X, static_cast<int>(Y.lb()));
  if (f == "pow") return ibex::pow(X, Y);
  if (f == "add") return X + Y;
  if (f == "sub") return X - Y;
  if (f == "mul") return X * Y;
  if (f == "div") return X / Y;
  ADD_FAILURE() << "unknown func in grid: " << f;
  return Interval::EMPTY_SET;
}

// libm reference for a single real input. MUST run under FE_TONEAREST.
// Returns false if the function is undefined / not a useful reference at x
// (then the sample is skipped for enclosure -- not a fallback, just not a
// point we can reference).
bool TrueAt(const Case& c, double x, double* out) {
  const std::string& f = c.func;
  double r;
  if (f == "sin") r = std::sin(x);
  else if (f == "cos") r = std::cos(x);
  else if (f == "tan") r = std::tan(x);
  else if (f == "exp") r = std::exp(x);
  else if (f == "log") { if (x <= 0.0) return false; r = std::log(x); }
  else if (f == "asin") { if (x < -1.0 || x > 1.0) return false; r = std::asin(x); }
  else if (f == "acos") { if (x < -1.0 || x > 1.0) return false; r = std::acos(x); }
  else if (f == "atan") r = std::atan(x);
  else if (f == "sinh") r = std::sinh(x);
  else if (f == "cosh") r = std::cosh(x);
  else if (f == "tanh") r = std::tanh(x);
  else if (f == "sqrt") { if (x < 0.0) return false; r = std::sqrt(x); }
  else return false;  // binary funcs referenced separately
  // Reject any non-finite libm result: where libm overflows/saturates (e.g.
  // cosh near the overflow threshold) it is not a valid reference -- gaol may
  // legitimately stay finite there -- so the sample is skipped, not asserted.
  if (!std::isfinite(r)) return false;
  *out = r;
  return true;
}

// Sample points for enclosure: endpoints, midpoint, analytic extrema in range,
// and a sweep of interior points. Only finite samples are emitted.
std::vector<double> SamplePoints(const Case& c) {
  std::vector<double> pts;
  const double a = c.x.lb();
  const double b = c.x.ub();
  auto add = [&](double v) {
    if (std::isfinite(v) && v >= a && v <= b) pts.push_back(v);
  };
  add(a);
  add(b);
  if (std::isfinite(a) && std::isfinite(b)) {
    const int kN = 64;
    for (int i = 1; i < kN; ++i) {
      add(a + (b - a) * (static_cast<double>(i) / kN));
    }
  } else {
    // Unbounded: sample some large magnitudes inside.
    for (double m : {0.0, 1.0, -1.0, 10.0, -10.0, 1e6, -1e6, 1e12, -1e12}) {
      add(m);
    }
  }
  // Analytic extrema: cos extrema at k*pi, sin extrema at pi/2 + k*pi.
  if (std::isfinite(a) && std::isfinite(b)) {
    if (c.func == "cos") {
      for (long k = static_cast<long>(std::floor(a / kPi)) - 1;
           k <= static_cast<long>(std::ceil(b / kPi)) + 1; ++k) {
        add(k * kPi);
      }
    } else if (c.func == "sin") {
      for (long k = static_cast<long>(std::floor(a / kPi)) - 1;
           k <= static_cast<long>(std::ceil(b / kPi)) + 1; ++k) {
        add(kPi / 2 + k * kPi);
      }
    }
  }
  return pts;
}

// A few-ulp tolerance scaled to the magnitude of v (absorbs libm's own ~1 ulp
// reference error -- see header).  Generous on purpose: layer (B) is the coarse
// soundness net, layer (A) is the exact gate.  Relative form (m * eps * ulps)
// is overflow-safe for every finite m -- distributing the multiply over a
// nextafter difference would overflow to inf-inf=NaN near DBL_MAX.
double UlpSlack(double v, int ulps) {
  const double m = std::abs(v);
  if (m == 0.0) return ulps * kDenormMin;
  return ulps * m * std::numeric_limits<double>::epsilon();
}

constexpr int kEnclosureUlps = 4;

// ---------------------------------------------------------------------------
// Golden table (captured from the baseline). Self-describing: each record holds
// the input endpoint bits, so the bit-identity check reconstructs inputs without
// depending on BuildGrid().
// ---------------------------------------------------------------------------
struct Golden {
  const char* func;
  uint64_t xlo, xhi, ylo, yhi;
  uint64_t olo, ohi;
};

#if defined(__has_include)
#if __has_include("gaol_transcendental_golden.inc")
#define DREAL_HAVE_GAOL_GOLDEN 1
const Golden kGolden[] = {
#include "gaol_transcendental_golden.inc"
};
#endif
#endif

// ---------------------------------------------------------------------------
// (A) Bit-identity: recompute every golden case, assert exact output bits.
// ---------------------------------------------------------------------------
TEST(GaolTranscendentalBitIdentity, MatchesBaselineGolden) {
#ifndef DREAL_HAVE_GAOL_GOLDEN
  GTEST_SKIP() << "golden not generated yet; run DISABLED_Generate on baseline "
                  "and commit gaol_transcendental_golden.inc";
#else
  const UpwardRoundingScope scope;
  const size_t n = sizeof(kGolden) / sizeof(kGolden[0]);
  ASSERT_GT(n, 0u);
  for (size_t i = 0; i < n; ++i) {
    const Golden& gd = kGolden[i];
    Case c;
    c.func = gd.func;
    c.x = Interval(FromBits(gd.xlo), FromBits(gd.xhi));
    c.y = Interval(FromBits(gd.ylo), FromBits(gd.yhi));
    c.binary = (gd.ylo != Bits(0.0) || gd.yhi != Bits(0.0));
    const Interval r = Apply(c);
    EXPECT_EQ(Bits(r.lb()), gd.olo)
        << "lb mismatch at #" << i << " func=" << gd.func
        << " got=" << r.lb() << " (0x" << std::hex << Bits(r.lb())
        << ") want=0x" << gd.olo << std::dec;
    EXPECT_EQ(Bits(r.ub()), gd.ohi)
        << "ub mismatch at #" << i << " func=" << gd.func
        << " got=" << r.ub() << " (0x" << std::hex << Bits(r.ub())
        << ") want=0x" << gd.ohi << std::dec;
  }
#endif
}

// ---------------------------------------------------------------------------
// (B) Independent enclosure (+ point tightness). Golden-independent.
// ---------------------------------------------------------------------------
TEST(GaolTranscendentalSoundness, EnclosesLibmReference) {
  const std::vector<Case> grid = BuildGrid();
  for (size_t i = 0; i < grid.size(); ++i) {
    const Case& c = grid[i];
    if (c.binary) continue;  // unary enclosure here; binary checked below

    Interval r;
    {
      const UpwardRoundingScope scope;
      r = Apply(c);
    }
    if (r.is_empty()) continue;

    const std::vector<double> pts = SamplePoints(c);
    double smin = kInf, smax = -kInf;
    bool reference_complete = true;  // false if libm couldn't reference a sample
    {
      const NearestRoundingScope scope;
      for (double x : pts) {
        double t;
        if (!TrueAt(c, x, &t)) {
          reference_complete = false;  // e.g. libm overflow near cosh threshold
          continue;
        }
        const double slack = UlpSlack(t, kEnclosureUlps);
        EXPECT_LE(r.lb() - slack, t)
            << "enclosure(lb) #" << i << " " << c.func << " x=" << x
            << " f(x)=" << t << " lb=" << r.lb();
        EXPECT_GE(r.ub() + slack, t)
            << "enclosure(ub) #" << i << " " << c.func << " x=" << x
            << " f(x)=" << t << " ub=" << r.ub();
        smin = std::min(smin, t);
        smax = std::max(smax, t);
      }
    }

    // Tightness (point inputs only) -- a COARSE catastrophic-width floor, not a
    // tight ulp bound. A genuinely tight independent bound is not achievable
    // across all regimes: sin/cos near a zero are absolute-limited by argument
    // reduction (pi is inexact, so e.g. sin(point) straddles 0 with ~1e-16
    // width -- correct and sound, not tight); ulp-distance explodes across 0
    // where doubles are dense; and sampled width on wide intervals underestimates
    // the true image. The EXACT tightness gate for the levers is layer (A): any
    // width change is a changed golden bit. This floor only catches a baseline
    // producing an absurdly wide point interval.
    const bool point_input = (Bits(c.x.lb()) == Bits(c.x.ub()));
    if (point_input && std::isfinite(r.lb()) && std::isfinite(r.ub())) {
      const double mag = std::max(std::abs(r.lb()), std::abs(r.ub()));
      const double width = r.ub() - r.lb();
      // max(absolute floor for arg-reduction near zeros, relative for big mag).
      const double allow = std::max(1e-9, 64.0 * mag *
                                              std::numeric_limits<double>::epsilon());
      EXPECT_LE(width, allow)
          << "point tightness (catastrophic floor) #" << i << " " << c.func
          << " width=" << width << "  [" << r.lb() << ", " << r.ub() << "]";
    }
  }
}

// Binary-op enclosure: the gaol interval must contain f(x,y) for sampled
// endpoints/interior of both operands.
TEST(GaolTranscendentalSoundness, BinaryEnclosesReference) {
  const std::vector<Case> grid = BuildGrid();
  for (size_t i = 0; i < grid.size(); ++i) {
    const Case& c = grid[i];
    if (!c.binary) continue;

    Interval r;
    {
      const UpwardRoundingScope scope;
      r = Apply(c);
    }
    if (r.is_empty() || !std::isfinite(r.lb()) || !std::isfinite(r.ub())) continue;

    auto samples = [](const Interval& I) {
      std::vector<double> v{I.lb(), I.ub(), I.mid()};
      if (std::isfinite(I.lb()) && std::isfinite(I.ub())) {
        v.push_back(I.lb() + 0.25 * (I.ub() - I.lb()));
        v.push_back(I.lb() + 0.75 * (I.ub() - I.lb()));
      }
      return v;
    };
    const std::vector<double> xs = samples(c.x);
    const std::vector<double> ys = samples(c.y);
    const NearestRoundingScope scope;
    for (double x : xs) {
      for (double y : ys) {
        double t;
        if (c.func == "add") t = x + y;
        else if (c.func == "sub") t = x - y;
        else if (c.func == "mul") t = x * y;
        else if (c.func == "div") { if (y == 0.0) continue; t = x / y; }
        else if (c.func == "pow_int") t = std::pow(x, static_cast<int>(c.y.lb()));
        else if (c.func == "pow") { if (x <= 0.0) continue; t = std::pow(x, y); }
        else continue;
        if (!std::isfinite(t)) continue;
        const double slack = UlpSlack(t, kEnclosureUlps);
        EXPECT_LE(r.lb() - slack, t)
            << "bin enclosure(lb) #" << i << " " << c.func
            << " x=" << x << " y=" << y << " t=" << t << " lb=" << r.lb();
        EXPECT_GE(r.ub() + slack, t)
            << "bin enclosure(ub) #" << i << " " << c.func
            << " x=" << x << " y=" << y << " t=" << t << " ub=" << r.ub();
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Golden generator. DISABLED so it never runs in ctest; invoke explicitly on the
// BASELINE build to (re)capture the golden. Writes C-initializer records.
// ---------------------------------------------------------------------------
TEST(GaolTranscendentalBitIdentity, DISABLED_Generate) {
  const char* out = std::getenv("GAOL_GOLDEN_OUT");
  const std::string path = out ? out : "gaol_transcendental_golden.inc";
  FILE* fp = std::fopen(path.c_str(), "w");
  ASSERT_NE(fp, nullptr) << "cannot open " << path;
  std::fprintf(fp,
               "// AUTO-GENERATED from the baseline gaol build. Do not edit by "
               "hand.\n"
               "// Regenerate: see gaol_transcendental_bitidentity_test.cc "
               "header.\n");

  const std::vector<Case> grid = BuildGrid();
  const UpwardRoundingScope scope;
  for (const Case& c : grid) {
    const Interval r = Apply(c);
    std::fprintf(
        fp,
        "{\"%s\", 0x%016llxull, 0x%016llxull, 0x%016llxull, 0x%016llxull, "
        "0x%016llxull, 0x%016llxull},  // %s [%g,%g]",
        c.func.c_str(), (unsigned long long)Bits(c.x.lb()),
        (unsigned long long)Bits(c.x.ub()), (unsigned long long)Bits(c.y.lb()),
        (unsigned long long)Bits(c.y.ub()), (unsigned long long)Bits(r.lb()),
        (unsigned long long)Bits(r.ub()), c.func.c_str(), c.x.lb(), c.x.ub());
    if (c.binary) std::fprintf(fp, " (y=[%g,%g])", c.y.lb(), c.y.ub());
    std::fprintf(fp, " -> [%g,%g]\n", r.lb(), r.ub());
  }
  std::fclose(fp);
  std::fprintf(stderr, "[generator] wrote %zu records to %s\n", grid.size(),
               path.c_str());
}

}  // namespace
}  // namespace dreal
