// this used to be auto-generated by Bazel

#ifndef VERSION_H
#define VERSION_H

#define DREAL_VERSION_STRING "4.21.06.2"
#define DREAL_VERSION_FULL      4
#define DREAL_VERSION_MAJOR    21
#define DREAL_VERSION_MINOR    06
#define DREAL_VERSION_REVISION  2

#endif //VERSION_H
