// this used to be auto-generated by Bazel

#ifndef VERSION_H
#define VERSION_H

#define DREAL_VERSION_FULL      5
#define DREAL_VERSION_MAJOR    00
#define DREAL_VERSION_MINOR    00
#define DREAL_VERSION_REVISION  1

#define DREAL_EXPERIMENTAL_SAT_MODEL_FULL_CONSTRAINTS false

// #define DREAL_EXPERIMENTAL_PM_USE_TRIE_IMPL
#define DREAL_EXPERIMENTAL_PM_USE_MAP_IMPL

#define DREAL_EXPERIMENTAL_THEORY_AUDIT_ENABLED  false
#define DREAL_EXPERIMENTAL_PM_DUMP_ALL_ENABLED   false
#define DREAL_EXPERIMENTAL_SAT_AUDIT_ENABLED     false

#define CAV26_FILTER_SYMMETRIES       false
#if CAV26_FILTER_SYMMETRIES
#define CAV26_VARNAME_PARSER          CAV26_SAR_PARSER
#define CAV26_MATCH_PURE_TIME_SYM     false
#define CAV26_MATCH_PURE_LOGIC_SYM    false

#endif

// check that options are required and mutually exclusive
#ifdef DREAL_EXPERIMENTAL_PM_USE_TRIE_IMPL
constexpr int pm_impl_mode = 0;
#endif
#ifdef DREAL_EXPERIMENTAL_PM_USE_MAP_IMPL
constexpr int pm_impl_mode = 1;
#endif

#endif //VERSION_H
