// this used to be auto-generated by Bazel

#ifndef VERSION_H
#define VERSION_H

#define DREAL_VERSION_FULL      5
#define DREAL_VERSION_MAJOR    00
#define DREAL_VERSION_MINOR    00
#define DREAL_VERSION_REVISION  1

#define DREAL_EXPERIMENTAL_SAT_MODEL_PARTIAL_CONSTRAINTS
// #define DREAL_EXPERIMENTAL_SAT_MODEL_FULL_CONSTRAINTS

#define DREAL_EXPERIMENTAL_THEORY_AUDIT_ENABLED  false
#define DREAL_EXPERIMENTAL_PM_DUMP_ALL_ENABLED   false
#define DREAL_EXPERIMENTAL_SAT_AUDIT_ENABLED     false

// #define DREAL_EXPERIMENTAL_GENERATE_HEURISTICS_CSV

// check that options are required and mutually exclusive
#ifdef DREAL_EXPERIMENTAL_SAT_MODEL_PARTIAL_CONSTRAINTS
constexpr int partial_model_mode = 1;
#endif
#ifdef DREAL_EXPERIMENTAL_SAT_MODEL_FULL_CONSTRAINTS
constexpr int partial_model_mode = 0;
#endif

#ifdef DREAL_EXPERIMENTAL_GENERATE_HEURISTICS_CSV
static_assert(pattern_matching_mode == 2);
#endif

#endif //VERSION_H
